############################################################################
# Contest 2026 team 000 hello app - Makefile
############################################################################

include $(APPDIR)/Make.defs

PROGNAME  = buggy_app
PRIORITY  = 50
STACKSIZE = 4096
MODULE    = $(CONFIG_LVX_USE_DEMO_CONTEST2026_000_HELLO_APP)

MAINSRC = buggy_app_main.c

include $(APPDIR)/Application.mk
